### ISSUE TITLE
Best way of retrieving Issuing Command in event handler?

### ISSUE THREAD

**Issue by mikaelj** [bytedreamer/OSDP.Net#100]
Since I have registered a manufacturer specific reply handler, I receive MfgReply both replied to from poll and from a specific MfgCommand. 

I need to distinguish between the two, and I can do that if I know what the reply was from. I see there's an Issuing Command which I can expose and add to the handler, but before I fork - is there a better / already supported way? I couldn't find any.

Thanks!

-----

I ended up exposing IssuingCommand in Reply and adding IssuingCommand as a parameter to ManufacturerSpecificReplyEventArgs.
Maybe it would be better to change the signature so it only receives the Reply, since the code already exctracts ConnectionId and Address. This would add a third (IssuingCommand) and by then it's simpler to just pass on the Reply.

**Comment by bytedreamer** [comment]
That IssuingCommand parameter might be useful to other clients of the library. I don't see any reason why it can't be merged.

Thanks for the feedback.

**Comment by bytedreamer** [comment]
A submission was never made for this issue, going ahead and closing it
