### ISSUE TITLE
Why was XWR and XRD removed in v3.0.0?

### ISSUE THREAD

**Issue by craftbyte** [bytedreamer/OSDP.Net#105]
I am trying to use this library for utilizing readers to read DESfire. I noticed that you removed XWR and XRD support in January when v3 got released. Is there a specific reason for this? I am specifically looking for support for the spec that is specified in v2.1.5 of the standed that works with HID readers, but adding support for v2.2 would be nice as well. Do you need help testing? I can provide readers and anything else if needed.

**Comment by bytedreamer** [comment]
I didn't want the open source project to be impacted by the HID patent by including the XWR and XRD commands. Please contact me at qubit@z-bitco.com for further discussions.
