### ISSUE TITLE
At Filetransfer, FtDelay seems not working as intended

### ISSUE THREAD

**Issue by Bobbbl** [bytedreamer/OSDP.Net#116]
When using OSDP_FILETRANSFER, the PD is allowed to request a timeout from the ACU. This time is specified in the FTSTAT response in bits 3 and 4 (see OSDP specification 2.2 section 7.25 -- FtDelay).
In this particular case a timeout of 5000 milliseconds is requested. The ACU responds by waiting an unspecified time (perhaps seconds instead of milliseconds?) and sending no further messages to the PD until the user is manually aborting the file transfer.

**Comment by bytedreamer** [comment]
Yes, it is implemented using milliseconds. The timeout request did work properly when tested with the Lenel BlueDiamond reader. I can double check the operation with the latest code. 

There is an option to capture the packets when call the StartConnection method. It would be helpful if you can attach the output file of a packet trace to this open issue.

**Comment by Bobbbl** [comment]
Thanks for looking into this!
I repeated the test with the latest release to be extra sure, as I got the precompiled console from a colleague of mine. I got the same kind of behavior. I have also done a log of the RS485 bus with a logic analyzer. I got the following behavior:

1. Console sends proper FTransfer message
2. PD replies with FTStat message
3. Console is stuck at 0% 
![image](https://user-images.githubusercontent.com/17763175/213636789-8803139b-d31a-4eed-b07b-573fb70f9247.png)
4. No more messages are sent

The PD reply is:
![image](https://user-images.githubusercontent.com/17763175/213636902-4581772b-9c16-435e-b7ef-9a10f3501d3d.png)
If I read this correctly, the FTStat message says:

| Name |  Code | Bit Order | Meaning |
|---|---|---|---|
|  FtAction  | 00h | - | Ok to proceed; No other action needed; No other activity |
| FtDelay   | 7017h  | LSB |  Wait 6000 ms (6s) |
|  FtStatusDetail  | 0000h | LSB | Ok to proceed |
|FtUpdateMsgMax  | 0000h | LSB | no change requested |

I'm testing against a developer version of an OSDP PD device, so it's possible that the PD has bugs here and there, but the answer looks good to me.

Thank you for all your efforts. Your tester is a great tool!

**Comment by Bobbbl** [comment]
Tested it with latest version. Filetransfer works now as expected.

![image](https://user-images.githubusercontent.com/17763175/215725776-7f3c4253-1fec-440f-b948-09899637f85b.png)

**Comment by bytedreamer** [comment]
Great, thanks for the update. I will close this issue and link it to the next release. I;m working to get it out this week.
