### ISSUE TITLE
Function to get the connection status of one of the device among  set of devices sharing same connection ID

### ISSUE THREAD

**Issue by DeepaGRao** [bytedreamer/OSDP.Net#126]
Hi,
We are using 3 devices connected to the same IP address and Port. But they are having different address and using the same connection ID. If one of the intermediate device is down, will the ControlPanel.IsOnline() function provide us the connection status of that particular device which is down?
Is there any other way to know that one out of the 3 device is down/Communication is offline? They are all using the same connection ID and other 2 devices status is online.

Regards,
Deepa

**Comment by bytedreamer** [comment]
There are two methods of getting the online status

For ad-hoc query, call IsOnline method from the ControlPanel object
```       
        /// <summary>
        /// Is the PD online
        /// </summary>
        /// <param name="connectionId">Identify the connection for communicating to the device</param>
        /// <param name="address">Address assigned to the device</param>
        /// <returns>Returns true if the PD is online</returns>
        public bool IsOnline(Guid connectionId, byte address)`
```

To get real-time status updates, subscribe to the ConnectionStatusChange event. An example of this is in the Test Console project

```     
     _controlPanel.ConnectionStatusChanged += (_, args) =>
            {
                DisplayReceivedReply(
                    $"Device '{_settings.Devices.SingleOrDefault(device => device.Address == args.Address, new DeviceSetting() { Name="[Unknown]"}).Name}' " +
                    $"at address {args.Address} is now " +
                    $"{(args.IsConnected ? (args.IsSecureChannelEstablished ? "connected with secure channel" : "connected with clear text") : "disconnected")}",
                    string.Empty);
            };
```

Let me know if there are any issues with either of these methods.

**Comment by DeepaGRao** [comment]
Thanks for this information. I used both these methods to get the status of the device. But when one device is down, IsOnline function is returning false for all the devices(with other address) which are using the same connection ID.
Please find the sample code and the screenshot of the output attached.
![CommunicationStatus](https://github.com/bytedreamer/OSDP.Net/assets/91255895/c5942ded-c1a7-497e-8527-fc1d0f79e8d6)
[SampleProgram.txt](https://github.com/bytedreamer/OSDP.Net/files/12091334/SampleProgram.txt)

**Comment by bytedreamer** [comment]
This is the same issue as #87 that you submitted earlier. I need to find out more about your hardware in order to figure out a resolution. Please contact me directly at qubit@z-bitco.com
