### ISSUE TITLE
Multiple serial connection is not allowed, at least I guess so

### ISSUE THREAD

**Issue by oguzselvi** [bytedreamer/OSDP.Net#128]
Normally when I use the default OSDP.Net software I start a serial connection then I add a device (OSDP card reader) and it works just fine but if I start a new serial connection, when I press the start button previous serial connection is cancelled and the gui says "........ device is disconnected" (the one I previously added with first serial connection). According to these experiences, I guess the default OSDP.Net software doesn't support multiple serial connections at the same time. 

I need to solve this problem because I have five different OSDP card reader and I allocated them into two different serial connections. Three of them are serial to each other and belong to COM1, other two of them are serial to each other and belong to COM2. When I run the OSDP.Net software I start a serial connection via interface, for example I start a serial connection via COM1 and add all three devices one by one (I marked "UseSecureChannel" false, while I was adding the devices, if I mark true, error pop out due to multiple card readers that are serially connected) . No problem so far, Then I start a new serial connection which is COM2 and suddenly I get error, and all the devices added previously are disconnected. After some debugging, I found out that If I comment the code segment below it would be okey to start a second serial connection. 

     private static async Task StartConnection(IOsdpConnection osdpConnection)
        {
            LastNak.Clear();

        //    if (_connectionId != Guid.Empty)                   // I commented these four lines
        //    {
        //        await _controlPanel.Shutdown();
        //    }

            _connectionId =
                _controlPanel.StartConnection(osdpConnection, TimeSpan.FromMilliseconds(_settings.PollingInterval),
                    _settings.IsTracing);

            foreach (var device in _settings.Devices)
            {
                _controlPanel.AddDevice(_connectionId, device.Address, device.UseCrc, device.UseSecureChannel,
                    device.SecureChannelKey);
            }
        }

        
As I expected, I managed to start a new serial connection and I didn't lose the connection of three devices belong to the first serial connection. Then I added the other two devices (card readers) belong to the COM2. At this point, I have 5 different properly working OSDP card readers, allocated into 2 different serial connections, their LED's turned green to blue and they all read the data of my dummy smart card. So far so good but then I realized I can send command through last added two device but I couldn't do the same with previous three card reader. Finally I figured it out, when a serial connection is created there is a two-way communication between card reader and OSDP.Net (card reader can send the data that is read to the OSDP.Net and OSDP.Net can send the command to the card reader) but after a second serial connection is started, the two-way communication of the first serial connection is downgraded to one-way communication which is card reader to OSDP.Net (card reader still sends the data that is read but OSDP.Net can't send command anymore). For the second serial connection, two-way communication is still valid but if I start I third serial connection second one will be downgraded to. So it is clear that with this version of the software I can have a proper setup with only one serial connection and this doesn't work for me. I need to have multiple serial connections, multiple card readers on each serial connection and two-way communication for all of them. 

Do you have any suggestion or comment? like, is this software able to be upgraded in this way? or my observations are correct? I may missunderstood somethings. I appreciate for any help. Best regards.

**Comment by bytedreamer** [comment]
The OSDP.Net library is designed to work with multiple serial ports with no issues. The UI in the test console on the other hand only supports connecting to one serial port at a time.

**Comment by bytedreamer** [comment]
Feel free to contact me directly at qubit@z-bitco.com for further discussions.

**Comment by oguzselvi** [comment]
Thanks for the quick reply Mr.Horvath, I will be looking into OSDP.Net library.
