### ISSUE TITLE
usbOsdpConnection

### ISSUE THREAD

**Issue by velasquezjc** [bytedreamer/OSDP.Net#160]
Hi, 
  Is there some usbOsdpConnection implementation?

**Comment by bytedreamer** [comment]
If you are using an USB to RS485 device, the SerialPortOsdpConnection would be adequate. The USB device should report as a standard serial port in the OS.

Please let me know if there is a different use case that needs to be addressed.

**Comment by AmrRahmy** [comment]
i tried two readers, one of them hid signo 20 using CH340 USB to RS485.

![51ygZNn4n4S _AC_SL1166_](https://github.com/bytedreamer/OSDP.Net/assets/9623123/b5e29b9b-40af-4516-af46-30237f751a84)

doesn't seem work with code or test app.

![Capture](https://github.com/bytedreamer/OSDP.Net/assets/9623123/b8f0f938-93b2-4499-a8d6-52cb0d71c4f4)

**Comment by bytedreamer** [comment]
It appears that you are having driver incompatibility issues. Check out the discussion about it here on StackOverflow.

https://stackoverflow.com/questions/76158517/serial-to-usb-cable-ch340-new-driver-not-functioning-with-c-sharp-applicatio

**Comment by AmrRahmy** [comment]
Just saw. I used an rs485 usb adapter with a ground pin, and that worked fine.

![71yNeQMaSIL _AC_SL1500_](https://github.com/user-attachments/assets/c9782a7e-0ad7-485b-85f0-1706bc332eb3)

**Comment by bytedreamer** [comment]
Great to hear that it worked with a different adapter. Thanks for the update
