### ISSUE TITLE
Extended write?

### ISSUE THREAD

**Issue by lexohcom** [bytedreamer/OSDP.Net#173]
Hello according to list of supported functions extended write is not supported, however in comment in issue #21

It was added.

I need to implement Mifare1 K read block but I am getting: Received NAK Error: Unknown Command Code

When ever I try to send a APDU command.

**Comment by bytedreamer** [comment]
Extended write had been removed because of patent concerns

**Comment by hesa2020** [comment]
> Extended write had been removed because of patent concerns

Can you contact me smartens@lexoh.com

To help understanding how it used to work.

I am unable to find any documentation about it.
