### ISSUE TITLE
Optimise dependency graph

### ISSUE THREAD

**Issue by thompson-tomo** [bytedreamer/OSDP.Net#178]
Only dependencies that are not capable of being provided as part of the framework should be an external dependency, this means STJ only included for net framework/standard

**Comment by bytedreamer** [comment]
@thompson-tomo Is there a Nuget dependency that you think is not needed?

**Comment by thompson-tomo** [comment]
@bytedreamer to make it easier to see i have just submitted #179 showing the slight change
