### ISSUE TITLE
Serial Number should be uint?

### ISSUE THREAD

**Issue by CoenraadS** [bytedreamer/OSDP.Net#187]
Hello

While converting some existing code to use this library, I noticed that `DeviceIdentification.SerialNumber` is an `int`.

Comparing against another open source library (libosdp), they defined it as a `uint`:
https://github.com/goToMain/libosdp/blob/master/include/osdp.h#L254

Unfortunately I don't have access to the standards document to know which one is correct.

btw I listened to you on the podcast and really appreciate this native c# library 👍

**Comment by bytedreamer** [comment]
The standard doesn't say explicitly what type is to be expected. It should be easy to convert to uint if needed.

Thanks
