### ISSUE TITLE
Support for smart card commands removed?

### ISSUE THREAD

**Issue by jraynes** [bytedreamer/OSDP.Net#21]
I bought a HID Signo 40k reader to test your library. It works great for basic functionality. However I was hoping to be able to send APDU commands to the card using the OSDP extended write command. It looks like you removed this functionality at some point, any reason why? Do you have plans to add it back?

**Comment by bytedreamer** [comment]
Thanks for the feedback. I don't have readers to properly test the commands for smart cards. I'll add them back in, once I can verify that it works properly. Does the new HID readers support the OSDP APDU commands? I'll see about getting a hold of one if it does.

**Comment by jraynes** [comment]
I just got off the phone with HID and they claim the Signo line should be fully compliant with the spec.

**Comment by jraynes** [comment]
@bytedreamer any update on this? I'd be happy to loan you my Signo 20k reader if it helps.

**Comment by bytedreamer** [comment]
@jraynes please contact via email to discuss further. It can be found in my profile page.

**Comment by bytedreamer** [comment]
Smart card support has been added with v2.0.0
