### ISSUE TITLE
Demo Package Works, Code Doesn't

### ISSUE THREAD

**Issue by sbouter-idsoftware** [bytedreamer/OSDP.Net#29]
The demo downloadable at https://www.z-bitco.com/downloads/OSDPTestConsole.zip works fine with our devices; however, downloading the source code and running it fails ("error while sending command" or "invalid size for the data" are common).

I'm at a loss why, unless the code is just so different. Thanks for your help in advance.

**Comment by bytedreamer** [comment]
The demo package gets uploaded anytime a new version of a NuGet package is published. The default branch is develop, which might have newer commits than what has been published. Right now they are the build from the same code. If you cloned the develop branch more than a week back, try pulling the latest. 

Which environment are you running the demo and code? Are they running on the same machine with the same port? Make sure they are not running at the same time.

**Comment by sbouter-idsoftware** [comment]
I did update to 1.0.7 yesterday just in case (was at 1.0.6). I’m using Visual Studio 2019—definitely making sure both apps aren’t running at the same time.

Attached are the views when I connect and do device capabilities in both “versions”.

-Sam

**Comment by bytedreamer** [comment]
Using email for response didn't include the screenshots. I typically do my development with MacOS and have had no issues. I pulled the latest with my Windows machine and also couldn't reproduce the issue. Double check that the connection settings has the correct baud rate and the devices have matching security settings.

**Comment by sbouter-idsoftware** [comment]
I just tried a Mac dev system--same problem. I'll forward the screenshots to your email. Settings have been checked and then checked some more. The fact that one works fine leads me to believe that everything is hooked up correctly.

Thanks,
Sam
________________________________

**Comment by bytedreamer** [comment]
Resolved with Release 1.0.8 fixes
