### ISSUE TITLE
Powershell 7 Errors

### ISSUE THREAD

**Issue by jraynes** [bytedreamer/OSDP.Net#31]
When trying to Load OSDP.Net.dll in Powershell 7 I get this error:

PS C:\Users\Justin\Downloads> Add-Type C:\users\justin\downloads\sample\sample\OSDP.Net.dll
Add-Type: (1,50): error CS0116: A namespace cannot directly contain members such as fields or methods
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
                                                 ^

Add-Type: (1,2): error CS1022: Type or namespace definition, or end-of-file expected
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
 ^

Add-Type: (1,3): error CS1009: Unrecognized escape sequence
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
  ^

Add-Type: (1,9): error CS1056: Unexpected character '\'
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
        ^

Add-Type: (1,16): error CS1056: Unexpected character '\'
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
               ^

Add-Type: (1,26): error CS1056: Unexpected character '\'
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
                         ^

Add-Type: (1,33): error CS1056: Unexpected character '\'
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
                                ^

Add-Type: (1,40): error CS1056: Unexpected character '\'
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
                                       ^

Add-Type: (1,1): error CS0116: A namespace cannot directly contain members such as fields or methods
C:\users\justin\downloads\sample\sample\OSDP.Net.dll
^

Add-Type: Cannot add type. Compilation errors occurred.
PS C:\Users\Justin\Downloads>

I can use the old school System.Reflection.Assembly::LoadFile method but when I try to use the library I get a different error about missing class System.IO.Ports

PS C:\Users\Justin\Downloads> [System.Reflection.Assembly]::LoadFile("C:\users\justin\downloads\sample\sample\OSDP.Net.dll")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\users\justin\downloads\sample\sample\OSDP.Net.dll

PS C:\Users\Justin\Downloads> $conn = [OSDP.Net.Connections.SerialPortOsdpConnection]::new("COM2",9600)
MethodInvocationException: Exception calling ".ctor" with "2" argument(s): "Could not load file or assembly 'System.IO.Ports, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified."
PS C:\Users\Justin\Downloads>

Oddly enough when I put [System.IO.Ports] into the command line I can tab through it with Intelisense so I know its installed properly.

**Comment by bytedreamer** [comment]
This command successfully loaded the assembly on my computer 

`Add-Type -Path ./OSDP.Net.dll`

**Comment by jraynes** [comment]
Yes, I can load the assembly but when I try to open the serial port I get an error about System.IO.Ports. Any idea on what may be causing that?

**Comment by bytedreamer** [comment]
The wrong version of System.IO.Port is loaded when PowerShell starts. This can be rectified by issuing the following command.

`Add-Type -AssemblyName "System.IO.Ports, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"`

**Comment by bytedreamer** [comment]
Let me know if the suggested command didn't fix the issue for your environment.

**Comment by jraynes** [comment]
The command runs but still get the same error when trying to open a connection with the OSDP library

**Comment by bytedreamer** [comment]
The logging abstractions dll also needs to have the correct version. Running the commands from the Console build output did allow me to open a connection. Here is the PowerShell script that worked on my MacBook.

```
cd /Users/bytedreamer/Projects/OSDP.Net/src/Console/bin/Debug/netcoreapp3.1
Add-Type -Path ./OSDP.Net.dll
Add-Type -AssemblyName "System.IO.Ports, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
Add-Type -AssemblyName "Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

$conn = [OSDP.Net.Connections.SerialPortOsdpConnection]::new("/dev/tty.usbserial-AB0JI236",9600)
$panel = [OSDP.Net.ControlPanel]::new()
$id = $panel.StartConnection($conn)
$panel.AddDevice($id, 0, 1, 1)
```

**Comment by jraynes** [comment]
same error. I guess its a windows thing.

**Comment by bytedreamer** [comment]
I tested on Windows 10 with .NET core loaded

<img width="794" alt="PowerShell On Windows" src="https://user-images.githubusercontent.com/2985653/105506069-a56af780-5c97-11eb-9384-7e3b6bfbad29.png">

**Comment by jraynes** [comment]
I don't know what I'm doing wrong here...

Tried on my Surface tablet which has bone stock windows 10, nothing on it. Installed Powershell 7.0.4 and .NET SDK 5.0.2. Back to add-type compile errors....

I'm still using the DLL from the SmartCardSample you provided a few weeks ago. Is there something different about that version and what you are using above?

Maybe visual studio includes something that I need to make this work?

**Comment by jraynes** [comment]
Downloaded visual studio 2019 and successfully built the library from source:

![image](https://user-images.githubusercontent.com/17382944/105608102-f5b58880-5d6f-11eb-983a-c75e8a7a3e0d.png)

But when I try to load it with add-type it fails:

![image](https://user-images.githubusercontent.com/17382944/105608151-4331f580-5d70-11eb-943a-1875276c1f2a.png)

**Comment by jraynes** [comment]
Nevermind, got it working by loading OSDP.Net like how you suggested I load system.io.ports

Add-Type -AssemblyName "osdp.net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

Interestingly enough I couldn't load System.IO.Ports that way but it doesn't matter. Your library is able to load that correctly on its own when imported correctly
