### ISSUE TITLE
Publish compiled binaries to releases

### ISSUE THREAD

**Issue by jraynes** [bytedreamer/OSDP.Net#33]
I'm not very familiar with Azure Pipelines but it shouldn't be too difficult to automatically publish the compiled binaries for both the library and the console application here in the releases section of this repo.

**Comment by bytedreamer** [comment]
The releases are managed by Nuget.org. I didn't consider formally releasing the console app. My original thought the Console app was  for folks who wanted a quick way to test and learn the OSDP.Net Lib. It is not a support app in it's own right.

I'm building a separate app used for configuring and diagnosing OSDP devices.
