### ISSUE TITLE
Secure channel not working since 2.0.6

### ISSUE THREAD

**Issue by ldholmgren** [bytedreamer/OSDP.Net#46]
Im in the process of updating our internal tools which have been using v1.0.4.

I'm running into some problems when trying to use secure channel on any release above 2.0.5. 
2.0.6-2.0.8 throws a SystemTimeoutException from ControlPanel.SendCommand(...) when sending any command.

With the latest version however (2.0.9) this is the result:
`Error while processing reply Connection ID: 4e600eda-773e-4aee-ba94-d73cbfd002e8 Address: 1 Type: CrypticData from address 1
System.Exception: Invalid client cryptogram
   at OSDP.Net.SecureChannel.Initialize(Byte[] clientRandomNumber, Byte[] clientCryptogram, Byte[] secureChannelKey)
   at OSDP.Net.Device.InitializeSecureChannel(Reply reply)
   at OSDP.Net.Bus.ProcessReply(Reply reply, Device device)
   at OSDP.Net.Bus.StartPollingAsync()`

This happens immediately at AddDevice(...)

From looking at respective release pr's, 2.0.6 had changes done to the secure channel handling. Guessing its something related to that? 

Dunno about 2.0.9 

Unsecured is working as expected.

**Comment by bytedreamer** [comment]
There was an issue with non default secure channel key throwing a connection error. A fix was added to resolve it in v2.0.8. 

Are you seeing the error using the default key or did you set it to something new? Are there multiple devices on the bus?

**Comment by bytedreamer** [comment]
K, I've put a fix in the source code for the issue you found. Try again with my changes. If you still have issues, try explicitly sending the default key.

My reader was sending back security NAKs when the key was null. The fix I submitted resolved the issue.

Thanks

**Comment by ldholmgren** [comment]
Still getting Invalid cryptogram. Using the defaultkey or explicitly adding it when adding the device makes no difference.

I'll try it against another device later when i have some time over.

**Comment by bytedreamer** [comment]
Any new information regarding this issue?

**Comment by ldholmgren** [comment]
havent had any time to spare for it yet,  our current implementation works without encryption, but we need it for a new tool this fall and hopefully ill have some time over in june/july to look into it more.

**Comment by bytedreamer** [comment]
@ldholmgren Have you found anything new regarding the hardware that is causing an SC issue? If there isn't an updated by the end of July, the issue will be closed.

**Comment by ldholmgren** [comment]
@bytedreamer  Plan is to start work on an update to our tool in the next 1-2 weeks, ill look into this issue then.

**Comment by bytedreamer** [comment]
Please test again with new version 2.0.12. I'm unable to reproduce the issue with the latest update.

**Comment by bytedreamer** [comment]
I'm closing this issue, as there has been no response
