### ISSUE TITLE
suggest document .net 3.0 core installation

### ISSUE THREAD

**Issue by rt-smithee** [bytedreamer/OSDP.Net#5]
if one loads this on an "empty" windows system you may not have .net core 3.0.  Suggestion: in the readme or elsewhere give some bit of hint as to what to retrieve from the Microsoft (or wherever) site to install this.

**Comment by bytedreamer** [comment]
With .NET Core 3.0, a single executable can be built with the all the required dependent components. I'll rebuild the next release with this option.

**Comment by bytedreamer** [comment]
The Readme file includes the location of the self executable files that includes all the required files.

**Comment by rt-smithee** [comment]
didn't work for me on some machines.
