### ISSUE TITLE
LED command has all zero parameters

### ISSUE THREAD

**Issue by rsgmodelworks** [bytedreamer/OSDP.Net#50]
In the current version the LED command uses all zero's as it's parameters which is not valid (PD returns NAK 9.)

**Comment by bytedreamer** [comment]
Are you referring to the console sending the LED command? The console will send zero the time/timer parameters to keep the color permanant.

I'm able to send LED command to a Wavelynx reader successfully.

**Comment by rsgmodelworks** [comment]
*not* how the spec reads to others.  this looks wrong, will follow up.

**Comment by bytedreamer** [comment]
The OSDP.Net lib doesn't restrict the input value of the timer fields. There shouldn't be any change needed for the library itself. The documentation will need to be updated to properly state the proper values for the LED command.

**Comment by bytedreamer** [comment]
This has been resolved with version 2.0.12
