### ISSUE TITLE
Can you please provide a sample on how to use OSDP.Net with secure sessions. I am able to connect to the device when secure channel is disabled. But I want to set up a secure session with the device for communication. Please provide a sample for encryptionkeyset method and Adddevice method with a securechannelkey

### ISSUE THREAD

**Issue by DeepaGRao** [bytedreamer/OSDP.Net#56]
Can you please provide a sample on how to use OSDP.Net with secure sessions. I am able to connect to the device when secure channel is disabled. But I want to set up a secure session with the device for communication.
I enabled secure mode on the device but not able to use EncryptionKeySet on the device.
Please provide a sample on how to use encryptionkeyset method and Adddevice method with a securechannelkey

**Comment by bytedreamer** [comment]
Good idea to update the Readme with a secure channel example. In your specific instance, did you establish a secure connection with the default key first? The KEYSET command can only be accepted if by the PD while the connection is secure.

**Comment by DeepaGRao** [comment]
Hi,
I have set the device to secure mode. Then started the connection as below:
 _connectionId = panel.StartConnection(new TcpClientOsdpConnection(IPAddr, port, baudRate));
Next, I am trying to set the Encryption key set using some key as below:
byte[] bytes = Encoding.ASCII.GetBytes("Deepa123");
await panel.EncryptionKeySet(_connectionId, deviceAddress, new EncryptionKeyConfiguration(KeyType.SecureChannelBaseKey, bytes));

I am getting the exception from the above call as "Sequence contains no matching element"

Can you please let me know if the above sequence is correct? Is there anything as default key?

**Comment by bytedreamer** [comment]
Two things

1. You need to establish a secure connection first. Use the default key if the key hasn't been set before.
2. The key needs to be 16 bytes in length.

**Comment by DeepaGRao** [comment]
Hi,
I am trying to use the default key since the key is not set before. I have used 16 bytes key as below. The device is also set to Secure Mode in the settings. When I try to use EncryptionKeySet command, I get the error - The operation has timed out. Any other hints on what could be the reason?
Below is the sample code used

byte[] bytes = new byte[]
                    {
                        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07
                    };
                panel.AddDevice(_connectionId, deviceAddress, true, true);
                bool successfulSet = await panel.EncryptionKeySet(_connectionId, deviceAddress, new EncryptionKeyConfiguration(KeyType.SecureChannelBaseKey, bytes));

**Comment by bytedreamer** [comment]
Closing because of no response
