### ISSUE TITLE
suggest add "poll" command

### ISSUE THREAD

**Issue by rt-smithee** [bytedreamer/OSDP.Net#6]
if you add a PD after the program is started it doesn't seem to find it and start polling.  if you start the program after the PD is running it seems fine.  Perhaps add a "poll now" command so it can "kick" a newly arrived PD?

**Comment by bytedreamer** [comment]
The latest commits has logic to handle this situation automatically. I will post a updated build shortly. Test it on your environment, and let me know the results.

**Comment by bytedreamer** [comment]
The latest build should start polling automatically as new PDs are added.

**Comment by bytedreamer** [comment]
I've been testing this situation with the latest code, and has been handling offline PD properly. No need to poll for PD, it will come online automatically.
