### ISSUE TITLE
CPU hog and logger flooding when connecting to invalid serial port

### ISSUE THREAD

**Issue by hallsbyra** [bytedreamer/OSDP.Net#64]
Commit https://github.com/bytedreamer/OSDP.Net/commit/c003ad68a080c81444ccfcbb6ef601c3af8b54e5 deletes the 5 second delay between connection retries (line 165/166). This results in CPU hogging and logger flooding in case e.g. trying to connect to an invalid serial port. 

I liked the delay! 😃

**Comment by bytedreamer** [comment]
Thanks for the feedback. I've been trying to balance having good performance without excessive delays when there is no response. Makes sense to put this one back in.

**Comment by bytedreamer** [comment]
Fixed in 2.0.18
