### ISSUE TITLE
Communication does not work if PD is added that is off line

### ISSUE THREAD

**Issue by kkanjuh** [bytedreamer/OSDP.Net#68]
Hi,

Since 2.0.17 if I add PD that is off line or if online device lost communication, all other communications stop.

Could you please check this?

Regards

**Comment by bytedreamer** [comment]
This should be fixed in the latest version released last night, 2.1.0

**Comment by kkanjuh** [comment]
Today I install this version. Problem is not solved.

**Comment by bytedreamer** [comment]
I've been unable to reproduce the issue as you described it in the earlier posting. Either provide more details regarding the environment or contact me directly through my business at z-bitco.com.

**Comment by kkanjuh** [comment]
When I replace in _SerialPortOsdpConnection_

        public async Task<int> ReadAsync(byte[] buffer, CancellationToken token)
        {
            return await _serialPort.BaseStream.ReadAsync(buffer, 0, buffer.Length, token).ConfigureAwait(false);
        }

with your old code

        public async Task<int> ReadAsync(byte[] buffer, CancellationToken token)
        {
            //_serialPort.RtsEnable = false;
            var task = _serialPort.BaseStream.ReadAsync(buffer, 0, buffer.Length, token);
            try
            {
                if (await Task.WhenAny(task, Task.Delay(-1, token)) == task)
                {
                    return await task.ConfigureAwait(false);
                }

                throw new OperationCanceledException();
            }
            catch
            {
                _serialPort.DiscardInBuffer();
                throw;
            }
        }

then for me everything works fine. With new code I also not receive disconnected event.

**Comment by bytedreamer** [comment]
The new 6.0 version of the SerialPort library removed the need to have extra logic to check for timeouts. I guess that this behavior doesn't work with earlier versions of .NET Framework. I will verify this weekend and revert if I can reproduce. What version of .NET is causing the problem?

**Comment by kkanjuh** [comment]
I use new 6.0

**Comment by bytedreamer** [comment]
Ok, I see the problem with Windows, however not on MacOS. I will add back the old logic until all the platforms handle cancel tokens properly. Thanks

**Comment by bytedreamer** [comment]
The issues should be fixed in 2.1.1

**Comment by kkanjuh** [comment]
> The issues should be fixed in 2.1.1

I make few short tests on Windows. It's work. Tomorow I will make test on Linux. Thank you.

**Comment by kkanjuh** [comment]
Work also on Linux
