### ISSUE TITLE
Query on Multi-drop

### ISSUE THREAD

**Issue by DeepaGRao** [bytedreamer/OSDP.Net#80]
Hi,
We have multi-dropped 3 devices and trying to use OSDP connection to read the data from PD.
DeviceAddress is set in each of those devices which can be used while adding device as below code .
panel.AddDevice(_connectionId, deviceAddress, true, true);

What should be given for the reader number? How can multi-drop devices be read using this OSDP.Net dll? Any samples for that?

Regards,
Deepa

**Comment by bytedreamer** [comment]
The OSDP standard allows multiple readers to be attached to single device. Read number is to identify a reader on a device with more than one. The reader number field is not related to having multi-drop devices on a bus. Unless the device has multiple readers attached, a value of one should be used.
